### ISSUE TITLE
Can i train on windows?

### ISSUE THREAD

**Issue by red-gezi** [longzw1997/Open-GroundingDino#36]
i try to run 
bash train_dist.sh  1 config/cfg_odvg.py config/datasets_mixed_odvg.json ./logs
but

Traceback (most recent call last):
  File "E:\VSProject\Open-GroundingDino\main.py", line 372, in <module>
    main(args)
  File "E:\VSProject\Open-GroundingDino\main.py", line 88, in main
    utils.setup_distributed(args)
  File "E:\VSProject\Open-GroundingDino\util\misc.py", line 553, in setup_distributed
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "D:\python\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "D:\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in

and i found that Windows doesn't seem to support NCCL. Are there any other ways to train on Windows?

**Comment by BIGBALLON** [comment]
I'm sorry, we haven't tested it on Windows. By the way, using Windows may introduce additional issues. It is recommended that you perform the training on Linux.
