### ISSUE TITLE
IndexError: index 909 is out of bounds for dimension 0 with size 900

### ISSUE THREAD

**Issue by WanFeng123313** [longzw1997/Open-GroundingDino#41]
我在我自己的数据集上训练，完整报错如下：
Traceback (most recent call last):
  File "/mnt/lvm_data/project/xyguo/code_dmx/Open-GroundingDino/main.py", line 372, in <module>
    main(args)
  File "/mnt/lvm_data/project/xyguo/code_dmx/Open-GroundingDino/main.py", line 284, in main
    train_stats = train_one_epoch(
  File "/mnt/lvm_data/project/xyguo/code_dmx/Open-GroundingDino/engine.py", line 48, in train_one_epoch
    loss_dict = criterion(outputs, targets, cap_list, captions)
  File "/mnt/lvm_data/public/package/anaconda3/envs/groundingdino_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/lvm_data/project/xyguo/code_dmx/Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 596, in forward
    tgt_ids[i]=tgt_ids[i][indices[i][1]]
IndexError: index 909 is out of bounds for dimension 0 with size 900

通过翻阅代码，发现应该下图中的两行代码产生的索引值超出了for循环中tgt_ids[i]的长度，请问应该怎么改呢?
![image](https://github.com/longzw1997/Open-GroundingDino/assets/81793539/72cfdb22-8eb0-4fd1-be76-95f3ed633787)

**Comment by longzw1997** [comment]
Could you please provide more details? For example, the specific values of tgt_ids and indices.

**Comment by WanFeng123313** [comment]
> I met the same problem. Have you found a solution？

I suspected that the number of instances in the image could not be more than the number of queries (is 900), so I deleted all the images with more than 900 instances in the dataset and can now train normally

**Comment by QzYER** [comment]
> > I met the same problem. Have you found a solution？
> 
> I suspected that the number of instances in the image could not be more than the number of queries (is 900), so I deleted all the images with more than 900 instances in the dataset and can now train normally

this is my  train logs：
Some weights of BertModel were not initialized from the model checkpoint at bert_base_uncased and are newly initializedense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "main.py", line 372, in <module>
    main(args)
  File "main.py", line 144, in main
    model, criterion, postprocessors = build_model_main(args)
  File "main.py", line 81, in build_model_main
    model, criterion, postprocessors = build_func(args)
  File "/home/quchunguang/003-large-model/Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 804, in buil
    postprocessors = {'bbox': PostProcess(num_select=args.num_select  , text_encoder_type=args.text_encoder_type,nms_i,args=args)}
  File "/home/quchunguang/003-large-model/Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 665, in __in
    new_pos_map[v] = pos_map[k]
IndexError: index 1 is out of bounds for dimension 0 with size 1

i have only 1 class ，but i get the same question with you  ，but my datasets have no object 。

**Comment by VolkaJ** [comment]
I've encountered the same problem.


Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 665, in __init__
    new_pos_map[v] = pos_map[k]
IndexError: index 4 is out of bounds for dimension 0 with size 4
[2024-04-04 22:49:30,375] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 26121) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
