### ISSUE TITLE
我应该怎么训练自己的数据集

### ISSUE THREAD

**Issue by TaBeti** [longzw1997/Open-GroundingDino#63]
我使用COCO格式进行训练时一直报错：
Traceback (most recent call last):
  File "main.py", line 372, in <module>
    main(args)
  File "main.py", line 262, in main
    test_stats, coco_evaluator = evaluate(model, criterion, postprocessors,
  File "D:\Anaconda\envs\SAM\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Open-GroundingDino\engine.py", line 161, in evaluate
    for samples, targets in metric_logger.log_every(data_loader, 10, header, logger=logger):
  File "D:\Open-GroundingDino\util\misc.py", line 238, in log_every
    for obj in iterable:
  File "D:\Anaconda\envs\SAM\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\SAM\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\SAM\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\SAM\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Open-GroundingDino\datasets\coco.py", line 361, in __getitem__
    img, target = super(CocoDetection, self).__getitem__(idx)
  File "D:\Anaconda\envs\SAM\lib\site-packages\torchvision\datasets\coco.py", line 48, in __getitem__
    image = self._load_image(id)
  File "D:\Open-GroundingDino\datasets\coco.py", line 348, in _load_image
    path = self.coco.loadImgs(id)[0]["file_name"]
  File "D:\Anaconda\envs\SAM\lib\site-packages\pycocotools\coco.py", line 227, in loadImgs
    return [self.imgs[id] for id in ids]
  File "D:\Anaconda\envs\SAM\lib\site-packages\pycocotools\coco.py", line 227, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: '1'

**Comment by VolkaJ** [comment]
How did you solve the problem?
